### PR TITLE
TypeScript, React Hook, Functional Components

### PR DESCRIPTION
**Pull request by sergeyt**
* React 16
* target ES6
* update all dependencies
* remove wrapper since it is useless

TODO:
* [ ] fix tests
* [ ] bundle type declarations using dts-bundle

---
This change is [Reviewable](https://reviewable.io/reviews/chrisbolin/react-detect-offline/63)

### CODE REVIEW

**Comment by sergeyt** [comment]
@chrisbolin any interest?

**Comment by chrisbolin** [comment]
Sure, let me go through it!

**Comment by sergeyt** [comment]
@chrisbolin great, regarding tests I am thinking to remove `enzyme` and replace it with standard `react-test-renderer`

**Comment by ilyakatz** [comment]
Great PR, would be nice to see this merged in!

**Comment by chrisbolin** [comment]
@ilyakatz maybe you had more time to go thru it than i did. what do you like about it?

**Comment by ilyakatz** [comment]
I'm not sure that I can fully judge the quality, I was more commenting on the spirit of moving to TypeScript specifically. It's a great library and the first thing I wanted to do after installing it was to see if there are TS types and came across this PR

**Comment by cwise89** [comment]
Will be doing this from scratch. many changes planned.

**Pull request closed without merging**
